#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define NUMBER_OF_BASIS_FUNCTIONS (CONVERGENCE_ORDER*(CONVERGENCE_ORDER+1)/2)
#define NUMBER_OF_QUANTITIES 3

#define NUMBER_OF_DOFS (NUMBER_OF_BASIS_FUNCTIONS*NUMBER_OF_QUANTITIES)

#endif // CONSTANTS_H_
